#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DCOP
version:      0.031
version_from: DCOP.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
